# Generated by Django 5.2.6 on 2025-10-27 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0013_alter_patient_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('careperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='authentication.careperson')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='authentication.patient')),
            ],
            options={
                'unique_together': {('careperson', 'patient')},
            },
        ),
    ]
