# Generated by Django 5.2.6 on 2025-09-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_remove_user_country_remove_user_phone_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_code',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_token',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
