# Generated by Django 5.2.6 on 2025-09-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_user_reset_code_user_reset_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reset_token',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
