# Generated by Django 5.2.6 on 2025-10-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_user_role_patient_careperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='code',
            field=models.CharField(null=True, unique=True),
        ),
    ]
