# Generated by Django 5.2.6 on 2025-09-12 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
