# Generated by Django 5.2.6 on 2025-10-19 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0003_drug'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugAlternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substitute', models.CharField(max_length=255)),
                ('match_score', models.FloatField(blank=True, null=True)),
                ('drug_class', models.CharField(blank=True, max_length=255, null=True)),
                ('atc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('herbal_alternatives', models.TextField(blank=True, null=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='drugs.drug')),
            ],
        ),
    ]
