# Generated by Django 5.2.6 on 2025-10-19 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0004_drugalternative'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='drugalternative',
            unique_together={('drug', 'substitute')},
        ),
    ]
