# Generated by Django 5.2.6 on 2025-11-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0005_alter_drugalternative_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='is_finished',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
