# Generated by Django 5.2.6 on 2026-01-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0006_medication_is_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='smiles',
            field=models.TextField(blank=True, null=True),
        ),
    ]
