# Generated by Django 5.2.6 on 2026-01-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0007_drug_smiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('smiles', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='drug',
            name='smiles',
        ),
    ]
