# Generated by Django 5.2.6 on 2026-01-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0008_activeingredient_remove_drug_smiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='active_ingredient',
        ),
        migrations.AddField(
            model_name='drug',
            name='active_ingredients',
            field=models.ManyToManyField(blank=True, related_name='drugs', to='drugs.activeingredient'),
        ),
    ]
