# Generated by Django 5.2.6 on 2026-01-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0009_remove_drug_active_ingredient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeingredient',
            name='smiles',
            field=models.TextField(blank=True, null=True),
        ),
    ]
